automerge oss->ent on nighly basis
Merge latest oss/master into Enterprise master on nightly basis and
alert #team-nomad channel if merge or problems occur.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -2,6 +2,7 @@
 ### WARNING: DO NOT manually EDIT or MERGE this file, it is generated by 'make ci-config'.
 ### INSTEAD: Edit or merge the source in config/ then run 'make ci-config'.
 ### ***
+# Orb 'circleci/slack@3.2.0' resolved to 'circleci/slack@3.2.0'
 version: 2
 jobs:
   test-nomad:
@@ -420,6 +421,196 @@ jobs:
         command: make check
     - run:
         command: make checkscripts
+    environment:
+    - GOMAXPROCS: 1
+    - GOPATH: /go
+    - GOTESTSUM_JUNITFILE: /tmp/test-reports/results.xml
+    - NOMAD_SLOW_TEST: 1
+  merge-oss:
+    docker:
+    - image: golang:1.12.13
+    working_directory: /go/src/github.com/hashicorp/nomad
+    steps:
+    - add_ssh_keys:
+        fingerprints:
+        - c6:96:98:82:dc:04:6c:39:dd:ac:83:05:e3:15:1c:98
+    - checkout
+    - run:
+        command: |
+          set -eux -o pipefail
+          # FAIL_REASON is used in the slack message below.
+          # We don't add a custom reason for every case, just the common ones.
+          echo "export FAIL_REASON='for an unknown reason, @mahmood please investigate: $CIRCLE_BUILD_URL'" >> $BASH_ENV
+          #
+          # Configure Git
+          git config --global user.email "hashicorp-ci@users.noreply.github.com"
+          git config --global user.name "hashicorp-ci"
+
+          # Merge OSS master branch to Enterprise merge branch
+          git remote add oss https://github.com/hashicorp/nomad.git
+          git fetch oss
+          git_merge_branch="ci/oss-merge-$(date +%Y%m%d%H%M%S)"
+
+          git checkout -b "${git_merge_branch}"
+          latest_oss_commit="$(git rev-parse oss/master)"
+          message="Merge Nomad OSS branch 'master' at commit ${latest_oss_commit}"
+          if ! git merge -m "$message" oss/master; then
+            # try to merge common conflicting files
+            git status
+            git checkout --theirs CHANGELOG.md
+            git checkout --theirs version/version.go
+            git checkout --theirs command/agent/bindata_assetfs.go
+            git add CHANGELOG.md version/version.go command/agent/bindata_assetfs.go
+
+            # attempt merging again
+            if ! git commit -m "$message"; then
+              echo "export FAIL_REASON='because git was unable to auto-merge'" >> $BASH_ENV
+              exit 1
+            fi
+          fi
+
+          # sanity check - do basic compile build
+          if ! make GOTAGS="ent codegen_generated" pkg/linux_amd64/nomad ; then
+            echo "export FAIL_REASON='because nomad failed to compile after auto-merge'" >> $BASH_ENV
+            exit 1
+          fi
+
+          # now merge and push
+          git checkout master
+          git merge "${git_merge_branch}"
+          git push origin master
+        name: Merge Merge OSS master branch
+    - run:
+        command: |
+          echo 'export SLACK_BUILD_STATUS="fail"' >> $BASH_ENV
+        name: Slack - Setting Failure Condition
+        when: on_fail
+    - run:
+        command: |
+          echo 'export SLACK_BUILD_STATUS="success"' >> $BASH_ENV
+        name: Slack - Setting Success Condition
+        when: on_success
+    - run:
+        command: |
+          if [ -z "$BASH" ]; then
+            echo Bash not installed.
+            exit 1
+          fi
+        name: Provide error if non-bash shell
+    - run:
+        command: |
+          current_branch_in_filter=false
+
+          IFS="," read -ra BRANCH_FILTERS <<< ""
+
+          for i in "${BRANCH_FILTERS[@]}"; do
+            if [ "${i}" == "${CIRCLE_BRANCH}" ]; then
+              current_branch_in_filter=true
+            fi
+          done
+
+          if [ "x" == "x" ] || [ "$current_branch_in_filter" = true ]; then
+            # Provide error if no webhook is set and error. Otherwise continue
+            if [ -z "$SLACK_WEBHOOK_OSS_ENT_AUTOMERGE" ]; then
+              echo "NO SLACK WEBHOOK SET"
+              echo "Please input your SLACK_WEBHOOK value either in the settings for this project, or as a parameter for this orb."
+              exit 1
+            else
+              #Create Members string
+              if [ -n "" ]; then
+                IFS="," read -ra SLACK_MEMBERS <<< ""
+                for i in "${SLACK_MEMBERS[@]}"; do
+                  if [ $(echo ${i} | head -c 1) == "S" ]; then
+                    SLACK_MENTIONS="${SLACK_MENTIONS}<!subteam^${i}> "
+                  elif echo ${i} | grep -E "^(here|channel|everyone)$" > /dev/null; then
+                    SLACK_MENTIONS="${SLACK_MENTIONS}<!${i}> "
+                  else
+                    SLACK_MENTIONS="${SLACK_MENTIONS}<@${i}> "
+                  fi
+                done
+              fi
+              #If successful
+              if [ "$SLACK_BUILD_STATUS" = "success" ]; then
+                #Skip if fail_only
+                if [ true = true ]; then
+                  echo "The job completed successfully"
+                  echo '"fail_only" is set to "true". No Slack notification sent.'
+                else
+                  curl -X POST -H 'Content-type: application/json' \
+                    --data "{ \
+                              \"attachments\": [ \
+                                { \
+                                  \"fallback\": \":tada: The Nomad OSS -> ENT merge just happened automatically.
+          \", \
+                                  \"text\": \":tada: The Nomad OSS -> ENT merge just happened automatically.
+          \", \
+                                  \"fields\": [ \
+                                    { \
+                                      \"title\": \"Project\", \
+                                      \"value\": \"$CIRCLE_PROJECT_REPONAME\", \
+                                      \"short\": true \
+                                    }, \
+                                    { \
+                                      \"title\": \"Job Number\", \
+                                      \"value\": \"$CIRCLE_BUILD_NUM\", \
+                                      \"short\": true \
+                                    } \
+                                  ], \
+                                  \"actions\": [ \
+                                    { \
+                                      \"type\": \"button\", \
+                                      \"text\": \"Visit Job\", \
+                                      \"url\": \"$CIRCLE_BUILD_URL\" \
+                                    } \
+                                  ], \
+                                  \"color\": \"#1CBF43\" \
+                                } \
+                              ] \
+                            } " $SLACK_WEBHOOK_OSS_ENT_AUTOMERGE
+                  echo "Job completed successfully. Alert sent."
+                fi
+              else
+                #If Failed
+                curl -X POST -H 'Content-type: application/json' \
+                  --data "{ \
+                    \"attachments\": [ \
+                      { \
+                        \"fallback\": \":red_circle: The Nomad OSS -> ENT merge failed today $FAIL_REASON.
+          \", \
+                        \"text\": \":red_circle: The Nomad OSS -> ENT merge failed today $FAIL_REASON.
+          \", \
+                        \"fields\": [ \
+                          { \
+                            \"title\": \"Project\", \
+                            \"value\": \"$CIRCLE_PROJECT_REPONAME\", \
+                            \"short\": true \
+                          }, \
+                          { \
+                            \"title\": \"Job Number\", \
+                            \"value\": \"$CIRCLE_BUILD_NUM\", \
+                            \"short\": true \
+                          } \
+                        ], \
+                        \"actions\": [ \
+                          { \
+                            \"type\": \"button\", \
+                            \"text\": \"Visit Job\", \
+                            \"url\": \"$CIRCLE_BUILD_URL\" \
+                          } \
+                        ], \
+                        \"color\": \"#ed5c5c\" \
+                      } \
+                    ] \
+                  } " $SLACK_WEBHOOK_OSS_ENT_AUTOMERGE
+                echo "Job failed. Alert sent."
+              fi
+            fi
+          else
+            echo "Current branch is not included in only_for_branches filter; no status alert will be sent"
+          fi
+        name: Slack - Sending Status Alert
+        shell: /bin/bash
+        when: always
     environment:
     - GOMAXPROCS: 1
     - GOPATH: /go
@@ -877,6 +1068,18 @@ workflows:
             ignore:
             - /^.-ui\b.*/
             - stable-website
+  merge-oss:
+    jobs:
+    - merge-oss:
+        filters:
+          branches:
+            only: master
+    triggers:
+    - schedule:
+        cron: 0 12 * * 1-5
+        filters:
+          branches:
+            only: master
   website:
     jobs:
     - build-website:
